name: Docker

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'docker/Dockerfile'
      - '.github/workflows/docker.yml'
  release:
    types:
      - released

jobs:
  ci:
    name: ${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [focal, jammy]
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      PUSH_DOCKER_IMAGE: ${{ github.ref == 'refs/heads/master' || github.event_name == 'release' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker meta-information
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=ref,event=branch,prefix=${{ matrix.distro }}-
            type=raw,event=pr,prefix=${{ matrix.distro }}-,value=master
            type=semver,pattern={{major}}.{{minor}},prefix=${{ matrix.distro }}-
            
      # Step to evaluate and set the TAG variable. This repo uses main instead of master, this also sets PRs to use master
      - name: Set TAG variable
        id: set_tag
        run: |
          if [[ "${{ steps.meta.outputs.version }}" == "${{ matrix.distro }}-main" ]] || [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "TAG=${{ matrix.distro }}-master" >> $GITHUB_ENV
          else
            echo "TAG=${{ steps.meta.outputs.version }}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          build-args: TAG=${{ env.TAG }}
          push: ${{ env.PUSH_DOCKER_IMAGE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
